project:
  type: website
  output-dir: _site
  preview:
    browser: true
  render:
    - "index.qmd"
    - "about.qmd"
  resources: 
    - shinylive-sw.js

website:  
  title: "POTUS Economic Scorecard"
  repo-url: https://github.com/jhelvy/potus-econ-scorecard
  site-url: https://jhelvy.github.io/potus-econ-scorecard/
  repo-actions: [edit, issue]
  image: screenshot.png
  back-to-top-navigation: false
  open-graph:
    locale: es_ES
    site-name: https://jhelvy.github.io/potus-econ-scorecard/
  navbar:
    search: false
    left:
      - text: "Scorecard"
        file: index.qmd
      - text: "About"
        file: about.qmd
    right: 
      - icon: github
        href: https://github.com/jhelvy/potus-econ-scorecard
  page-footer:
    center:
      - text: "Site made with <a href='https://quarto.org/' target='_blank'><img src='https://quarto.org/favicon.png' width=12> quarto</a> and <a href='https://posit-dev.github.io/r-shinylive/' target='_blank'>shinylive</a>"

format:
  html:
    theme: morph
    page-layout: full
    toc: false
    compress: true

execute:
  freeze: auto
  cache: true

shinylive:
  packages:
    - shiny
    - ggplot2
    - dplyr
    - ggrepel
    - plotly
    - arrow
